# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Development branch CI/CD workflow

on:
  push:
    branches: [ "feature/development" ]
  pull_request:
    branches: [ "feature/development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout project code from the GitHub repo.
      - name: Checkout project...
        uses: actions/checkout@v2
      # Setup the JDK 8 Environemnt in the VM.
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      # Cache maven .m2 (for future builds, it automatically invalidate cache with a .pom hash)
      - name: Cache Maven .m2 packages...
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # Build and test the project..
      # TODO: Pass this test phase for a Docker image to do it.
      - name: Building and testing...
        run: mvn -B package -D skipTests
